name: F1TENTH ROS2 Simulation Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull F1TENTH Gym ROS Docker Image
      run: docker pull f1tenth_gym_ros:latest

    - name: Run F1TENTH Gym ROS Contailer
      run: |
        docker run -d --name f1tenth_sim \
          --network host \
          f1tenth/f1tenth_gym_ros:latest \
          bash -c "source /opt/ros/foxy/setup.bash && source /sim_ws/install/local_setup.bash && ros2 launch f1tenth_gym_ros gym_bridge_launch.py"

    - name: Wait for Simulator to Start
      run: sleep 10

    - name: Run Teleop Node (Optional)
      run: |
        docker exec f1tenth_sim bash -c "source /opt/ros/foxy/setup.bash && source /sim_ws/install/local_setup.bash && ros2 run teleop_twist_keyboard teleop_twist_keyboard" &
        TELEOP_PID=$!
        sleep 30  # Allow some time for manual control
        kill $TELEOP_PID
        - name: Capture Logs (if test fails)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: simulation-logs
          path: /sim_ws/install/log

    - name: Stop and Remove Container
      if: always()
      run: docker rm -f f1tenth_sim
