name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Cache ROS2 packages
      uses: actions/cache@v4
      with:
        path: /opt/ros
        key: ${{ runner.os }}-ros2-foxy-${{ hashFiles('**/install_10_ros2.sh') }}
        restore-keys: |
          ${{ runner.os }}-ros2-foxy-

    - name: Install ROS2
      run: |
        chmod +x install_10_ros2.sh
        ./install_10_ros2.sh
      timeout-minutes: 5

    - name: Install F1TENTH Simulator
      run: |
        chmod +x install_20_f1tenth_sim.sh
        ./install_20_f1tenth_sim.sh
      timeout-minutes: 10
