name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Cache ROS2 packages
      uses: actions/cache@v4
      with:
        path: /opt/ros
        key: ${{ runner.os }}-ros2-foxy-${{ hashFiles('**/install_10_ros2.sh') }}
        restore-keys: |
          ${{ runner.os }}-ros2-foxy-

    - name: Install ROS2
      run: |
        chmod +x install_10_ros2.sh
        ./install_10_ros2.sh
      timeout-minutes: 5

    - name: Cache F1TENTH dependencies
      uses: actions/cache@v4
      with:
        path: ~/sim_ws
        key: ${{ runner.os }}-f1tenth-${{ hashFiles('**/install_20_f1tenth_sim.sh') }}
        restore-keys: |
          ${{ runner.os }}-f1tenth-

    - name: Install F1TENTH Simulator
      run: |
        chmod +x install_20_f1tenth_sim.sh
        ./install_20_f1tenth_sim.sh
      timeout-minutes: 5

    - name: Install Xvfb for headless testing
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
      timeout-minutes: 5

    - name: install ros2_screenshots
      run: |
        pip3 install ros2_screenshots
      timeout-minutes: 5

    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV  # Use $GITHUB_ENV to set DISPLAY
        chmod +x run_30.sh
        nohup ./run_30.sh > /dev/null 2>&1 &
        echo $! > simulator.pid
      timeout-minutes: 5

    - name: Capture Screenshot
      run: |
        source /opt/ros/foxy/setup.bash
        sleep 5  # Give simulator time to start
        ros2_screenshot --output ~/screenshot.png
      timeout-minutes: 5

    - name: Terminate Simulator
      run: kill $(cat simulator.pid)

    - name: upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ~/screenshot.png
        retention-days: 7
        overwrite: true
